# Generated by Django 5.0.1 on 2024-01-26 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentcar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='pic',
            field=models.ImageField(default='none', upload_to='media/carphotos'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(),
        ),
    ]
