# Generated by Django 5.0.1 on 2024-01-26 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentcar', '0002_car_pic_alter_car_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='pic',
            field=models.ImageField(default='media/carphotos.error.jpg', upload_to='media/carphotos'),
        ),
    ]
